Inpainting/urls.py
from django.urls import path, include
from django.contrib import admin
 
from . import view
 
urlpatterns = [
    path('login/', view.login),
    # path('', view.index),
    path('register/', view.register),
    path('index/', view.index),
    path('download/', view.download),
    path('upload/', view.upload),
    path('inpainting/', view.inpainting), 
    path('logout/', view.logout),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('home.urls'))
]

dashboard/urls.py
from django.urls import path

from . import views
from .decorators import login_required


app_name = 'dashboard'

urlpatterns = [
    path('', login_required(views.WuWenListView.as_view()), name='wenwu_list'),
    path('create/', login_required(views.WenWuCreateView.as_view()), name='wenwu_create'),
    path('<int:pk>/', login_required(views.WenWuDetailView.as_view()), name='wenwu_detail'),
    path('<int:pk>/update/', login_required(views.WenWuUpdateView.as_view()), name='wenwu_update'),
    path('<int:pk>/delete/', login_required(views.WenWuDeleteView.as_view()), name='wenwu_delete'),

    path('category/', login_required(views.CategoryListView.as_view()), name='category_list'),
    path('category/create/', login_required(views.CategoryCreateView.as_view()), name='category_create'),
    path('category/<int:pk>/', login_required(views.CategoryDetailView.as_view()), name='category_detail'),
    path('category/<int:pk>/update/', login_required(views.CategoryUpdateView.as_view()), name='category_update'),
    path('category/<int:pk>/delete/', login_required(views.CategoryDeleteView.as_view()), name='category_delete')
]

home/urls.py
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index_view, name='index_view'),
    path('search/', views.search_view, name='index_view'),
    path('category/<int:pk>', views.category_view, name='category_view'),
    path('wenwu/<int:pk>', views.wenwu_view, name='wenwu_view'),
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

dashboard/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name='分类名称')
    created_at = models.DateTimeField(verbose_name='创建时间', default=timezone.now)

    def __str__(self):
        return self.title


class WenWu(models.Model):
    title = models.CharField(max_length=200, verbose_name='文物名称')
    intro = models.TextField(verbose_name='文物介绍')
    origin_picture = models.ImageField(verbose_name='原图')
    repair_picture = models.ImageField(verbose_name='修复图', upload_to='repair/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='分类')
    created_at = models.DateTimeField(verbose_name='创建时间', default=timezone.now)

    def __str__(self):
        return self.title

dashboard/forms.py
from django import forms
from .models import WenWu, Category


class WenWuForm(forms.ModelForm):
    class Meta:
        model = WenWu
        fields = '__all__'
        exclude = ['created_at']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        exclude = ['created_at']

dashboard/views.py
from django.shortcuts import render, HttpResponseRedirect

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import WenWu, Category
from .forms import WenWuForm, CategoryForm
from .tables import CategoryTable, WenWuTable

from django_tables2 import SingleTableView, RequestConfig

from Inpainting.models import User


# 注入 Ticket User 上下文模板变量
class TicketAndUserContentData:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        ticket = self.request.COOKIES.get('ticket')
        email = self.request.COOKIES.get('email')
        user = User.objects.filter(email=email).first()

        if not ticket or not user or not User.objects.filter(ticket=ticket).exists():
            return HttpResponseRedirect('/login/')

        context['ticket'] = ticket
        context['user'] = user
        return context


class WuWenListView(TicketAndUserContentData, SingleTableView):
    table_class = WenWuTable
    queryset = WenWu.objects.all()

    # 添加分页
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        t = self.table_class(data=self.queryset)
        RequestConfig(self.request, paginate={"per_page": 10}).configure(t)
        context['table'] = t
        return context


class WenWuCreateView(TicketAndUserContentData, CreateView):
    model = WenWu
    form_class = WenWuForm
    success_url = reverse_lazy('dashboard:wenwu_list')


class WenWuUpdateView(TicketAndUserContentData, UpdateView):
    model = WenWu
    form_class = WenWuForm
    success_url = reverse_lazy('dashboard:wenwu_list')


class WenWuDetailView(TicketAndUserContentData, DetailView):
    model = WenWu


class WenWuDeleteView(TicketAndUserContentData, DeleteView):
    model = WenWu
    success_url = reverse_lazy('dashboard:wenwu_list')


class CategoryListView(TicketAndUserContentData, SingleTableView):
    table_class = CategoryTable
    queryset = Category.objects.all()

    # 添加分页
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        t = self.table_class(data=self.queryset)
        RequestConfig(self.request, paginate={"per_page": 10}).configure(t)
        context['table'] = t
        return context


class CategoryCreateView(TicketAndUserContentData, CreateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('dashboard:category_list')


class CategoryUpdateView(TicketAndUserContentData, UpdateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('dashboard:category_list')


class CategoryDetailView(TicketAndUserContentData, DetailView):
    model = Category


class CategoryDeleteView(TicketAndUserContentData, DeleteView):
    model = Category
    success_url = reverse_lazy('dashboard:category_list')

dashboard/templates/dashboard/bs51_tables.html
{% extends 'django_tables2/bootstrap.html' %}
{% load django_tables2 %}
{% load i18n %}


{% block pagination.previous %}
<li class="page-item">
    <a class="page-link" href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}">
        上一页
    </a>
</li>
{% endblock pagination.previous %}


{% block pagination.next %}
<li class="page-item">
    <a class="page-link" href="{% querystring table.prefixed_page_field=table.page.next_page_number %}">
        下一页
    </a>
</li>
{% endblock pagination.next %}


{% block pagination.range %}
{% for p in table.page|table_page_range:table.paginator %}
<li class="page-item{% if table.page.number == p %} active{% endif %}">
    <a class="page-link" {% if p != '...' %}href="{% querystring table.prefixed_page_field=p %}" {% endif %}>
        {{ p }}
    </a>
</li>
{% endfor %}
{% endblock pagination.range %}

dashboard/templates/dashboard/category_confirm_delete.html
{% extends 'dashboard/layout.html' %}
{% load django_bootstrap5 %}

{% block tabs %}
<ul class="nav nav-tabs mb-3">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:category_list' %}">列表</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:category_create' %}">新增</a>
    </li>

    <li class="nav-item">
        <a class="nav-link active" aria-current="page">删除</a>
    </li>
</ul>
{% endblock %}

{% block box %}
<p>您确定要删除 "{{ category }}" 吗?</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_button button_type="submit" content="确认删除" button_class="btn-danger" %}
</form>
{% endblock %}

dashboard/templates/dashboard/category_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

dashboard/templates/dashboard/category_form.html
{% extends 'dashboard/layout.html' %}
{% load django_bootstrap5 %}

{% block tabs %}
<ul class="nav nav-tabs mb-3">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:category_list' %}">列表</a>
    </li>

    {% if object %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:category_create' %}">新增</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page">编辑</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link active" aria-current="page">新增</a>
    </li>
    {% endif %}
</ul>
{% endblock %}


{% block box %}
<form action="" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="保存" button_class="btn-success" %}
    {% bootstrap_button button_type="reset" content="重置" button_class="btn-secondary" %}
</form>
{% endblock %}

dashboard/templates/dashboard/category_list.html
{% extends 'dashboard/layout.html' %}
{% load django_tables2 %}

{% block tabs %}
<ul class="nav nav-tabs mb-2">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">列表</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:category_create' %}">新增</a>
    </li>
</ul>
{% endblock %}

{% block box %}
{% render_table table %}
{% endblock %}

dashboard/templates/dashboard/layout.html
{% extends 'base.html' %}


{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col-2">
            {% include 'dashboard/menus.html' %}
        </div>
        <div class="col">
            {% block tabs %}{% endblock %}
            {% block box %}{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/menus.html
<div class="list-group">
    <a class="list-group-item list-group-item-action" href="{% url 'dashboard:wenwu_list' %}">文物管理</a>
    <a class="list-group-item list-group-item-action" href="{% url 'dashboard:category_list' %}">分类管理</a>
</div>

dashboard/templates/dashboard/wenwu_confirm_delete.html
{% extends 'dashboard/layout.html' %}
{% load django_bootstrap5 %}

{% block tabs %}
<ul class="nav nav-tabs mb-3">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:wenwu_list' %}">列表</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:wenwu_create' %}">新增</a>
    </li>

    <li class="nav-item">
        <a class="nav-link active" aria-current="page">删除</a>
    </li>
</ul>
{% endblock %}

{% block box %}
<p>您确定要删除 "{{ wenwu }}" 吗?</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_button button_type="submit" content="确认删除" button_class="btn-danger" %}
</form>
{% endblock %}

dashboard/templates/dashboard/wenwu_detail.html
{% extends 'dashboard/layout.html' %}
{% load django_bootstrap5 %}


{% block box %}
detail
{% endblock %}

dashboard/templates/dashboard/wenwu_form.html
{% extends 'dashboard/layout.html' %}
{% load django_bootstrap5 %}

{% block tabs %}
<ul class="nav nav-tabs mb-3">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:wenwu_list' %}">列表</a>
    </li>

    {% if object %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:wenwu_create' %}">新增</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page">编辑</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link active" aria-current="page">新增</a>
    </li>
    {% endif %}
</ul>
{% endblock %}


{% block box %}
<form action="" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="保存" button_class="btn-success" %}
    {% bootstrap_button button_type="reset" content="重置" button_class="btn-secondary" %}
</form>
{% endblock %}

dashboard/templates/dashboard/wenwu_list.html
{% extends 'dashboard/layout.html' %}
{% load django_tables2 %}

{% block tabs %}
<ul class="nav nav-tabs mb-2">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">列表</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:wenwu_create' %}">新增</a>
    </li>
</ul>
{% endblock %}

{% block box %}
{% render_table table %}
{% endblock %}