Inpainting/urls.py
from django.urls import path, include
from django.contrib import admin
 
from . import view
 
urlpatterns = [
    path('login/', view.login),
    # path('', view.index),
    path('register/', view.register),
    path('index/', view.index),
    path('download/', view.download),
    path('upload/', view.upload),
    path('inpainting/', view.inpainting), 
    path('logout/', view.logout),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('home.urls'))
]

dashboard/urls.py
from django.urls import path

from . import views
from .decorators import login_required


app_name = 'dashboard'

urlpatterns = [
    path('', login_required(views.WuWenListView.as_view()), name='wenwu_list'),
    path('create/', login_required(views.WenWuCreateView.as_view()), name='wenwu_create'),
    path('<int:pk>/', login_required(views.WenWuDetailView.as_view()), name='wenwu_detail'),
    path('<int:pk>/update/', login_required(views.WenWuUpdateView.as_view()), name='wenwu_update'),
    path('<int:pk>/delete/', login_required(views.WenWuDeleteView.as_view()), name='wenwu_delete'),

    path('category/', login_required(views.CategoryListView.as_view()), name='category_list'),
    path('category/create/', login_required(views.CategoryCreateView.as_view()), name='category_create'),
    path('category/<int:pk>/', login_required(views.CategoryDetailView.as_view()), name='category_detail'),
    path('category/<int:pk>/update/', login_required(views.CategoryUpdateView.as_view()), name='category_update'),
    path('category/<int:pk>/delete/', login_required(views.CategoryDeleteView.as_view()), name='category_delete')
]

home/urls.py
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index_view, name='index_view'),
    path('search/', views.search_view, name='index_view'),
    path('category/<int:pk>', views.category_view, name='category_view'),
    path('wenwu/<int:pk>', views.wenwu_view, name='wenwu_view'),
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CH">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="pragma" content="no-cache">
  <meta http-equiv="Cache-Control" content="no-cache, must-revalidate">
  <meta http-equiv="expires" content="0">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="shortcut icon" href="{% static 'media/icon.png' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
  <script type="text/javascript" src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
  <style>
    html,
    body {
      height: 100%;
      background-color: #f5f5f5;
      font-family: 'Roboto', sans-serif;
    }
  </style>
</head>


<body class="bg-light">

  {% include 'header.html' %}

  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }}" style="text-align: center;">
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}

  {% block content %}{% endblock %}

  <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

templates/download.html
{% extends 'base.html' %}
{% block title %} 古代壁画修复 | 下载 {% endblock title %}
{% load static %}
{% block content %}

<div class="container text-center pt-1">
  <h6 class="mt-3">
    <img class="mb-4" src="{% static 'media/smile.png' %}" alt="" width="40">
    图像修复完成！
  </h6>
  <div class="my-3">
    <img id="result_img" src="{{user.result_path}}" alt="result_img" height="256px">
  </div>
  <div>
    <button class="btn btn-secondary" id="back_home">
      <i class="bi bi-arrow-return-left"></i>
      取消返回
    </button>
    <button class="btn btn-warning" id="download_bt" style="margin:0 16px;">
      <i class="bi bi-download"></i>
      下载保存
    </button>
  </div>


  <h4 style="text-align: left;margin-top: 62px;margin-bottom: 32px;">修复效果：</h4>
  <div class="row row-cols-4 mt-2 text-center">
    <div class="col" style="float: none; margin-left: 100px;">
      <div class="card mb-4 rounded-3 shadow-sm border-dark">
        <div class="card-header text-white bg-dark border-dark">
          <h6 class="my-0 fw-normal">输入图像</h6>
        </div>
        <div class="card-body">
          <img id="result_img" src="{{user.upload_path}}" alt="result_img"
          style="width: 256px;height: 256px;object-fit: cover;">
        </div>
      </div>
    </div>
    <div class="col" style="margin-left: 65px; margin-right: 65px;">
      <div class="card mb-4 rounded-3 shadow-sm border-dark">
        <div class="card-header text-white bg-dark border-dark">
          <h6 class="my-0 fw-normal">掩模合成</h6>
        </div>
        <div class="card-body">
          <img id="result_img" src="{{user.masked_path}}" alt="result_img" height="256px">
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card mb-4 rounded-3 shadow-sm border-dark">
        <div class="card-header text-white bg-dark border-dark">
          <h6 class="my-0 fw-normal">输出图像</h6>
        </div>
        <div class="card-body">
          <img id="result_img" src="{{user.result_path}}" alt="result_img" height="256px">
        </div>
      </div>
    </div>
  </div>

</div>

<script src="{% static 'js/download.js' %}"></script>
{% endblock content %}

templates/header.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container">

        <a href="/" class="navbar-brand">
            <img src="{% static 'media/icon.png' %}" alt="robot" width="40" height="40"/>
            <span class="fs-5">数字化文物展示系统</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:wenwu_list' %}">管理</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/index/">修复</a>
                </li>
            </ul>
            <form class="d-flex me-3" method="get" action="/search/">
                <input class="form-control me-2" name="q" value="{{ request.GET.q }}" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <div class="d-flex">
                {% if ticket %}
                <span class="fs-5" style="color: white;">欢迎,{{ user.name }}&nbsp;&nbsp;&nbsp;</span>
                <button type="button" id="logout_bt" class="btn btn-outline-light me-2">退出</button>
                {% else %}
                <button type="button" id="login" class="btn btn-outline-light me-2">登录</button>
                <button type="button" id="register" class="btn btn-warning">注册</button>
                {% endif %}
            </div>
        </div>
    </div>

</nav>

<script type="text/javascript">
    let login = document.getElementById('login')
    let register = document.getElementById('register')
    if (login) {
        login.onclick = function () {
            window.location.replace('/login')
        }

        register.onclick = function () {
            window.location.replace('/register')
        }
    }


    let logout_bt = document.getElementById('logout_bt')
    if (logout_bt) {
        logout_bt.onclick = function () {
            window.location.replace('/logout')
        }
    }

</script>

templates/index.html
{% extends 'base.html' %}
{% block title %} 数字化文物展示系统 | 首页 {% endblock title %}
{% load static %}
{% block content %}

<div class="container text-center pt-5 my-3">
    <div>
        <input type="range" min="0" max="20" step="1" class="custom-range" id="customRange1" style="width: 200px">
    </div>
    <div class="my-3">
        <canvas id="canvas" style="position: absolute;"></canvas>
        <img id="upload_img" src="{{user.upload_path}}" alt="upload_img"
             style="width: 256px;height: 256px;object-fit: cover;object-position: center;">
    </div>
    <div style="width: 500px;text-align: left;margin: 0 auto; display: none;">
        <div class="mb-3">
            <label for="category_id" class="form-label">分类</label>
            <select class="form-select" name="category_id" id="category_id">
                {% for item in category %}
                <option value="{{ item.id }}">{{ item.title }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-3">
            <label for="title" class="form-label">名称</label>
            <input type="text" class="form-control" id="title" name="title">
        </div>
        <div class="mb-3">
            <label for="intro" class="form-label">简介</label>
            <textarea class="form-control" id="intro" name="intro" rows="3"></textarea>
        </div>
    </div>
    <div>

        <button class="btn btn-warning" id="clean"><i class="bi bi-eraser"></i> 擦除掩模</button>
        <input id="select_file" type="file" accept="image/jpg, image/jpeg, image/png, image/webp" hidden>
        <button class="btn btn-primary" id="upload_bt" style="margin:0 16px;">
            <i class="bi bi-upload"></i>
            上传图像
            <div class="spinner-border spinner-border-sm" id="upload_loading" role="status" style="display: none;">
                <span class="visually-hidden">Loading...</span>
            </div>
        </button>
        <button class="btn" id="inpainting" style="background-color: #19aa8d;color: white;">
            <i class="bi bi-tools"></i>
            开始修复
            <div class="spinner-border spinner-border-sm" id="inpainting_loading" role="status" style="display: none;">
                <span class="visually-hidden">Loading...</span>
            </div>
        </button>
    </div>

    <select id="img_type" class="form-select m-auto mt-3 text-center" style="width: 220px; display: none;">
        {% if user.img_type == 1 %}
        <option value="1" selected>算法 1</option>
        <option value="2">算法 2</option>
        {% else %}
        <option value="1">算法 1</option>
        <option value="2" selected>算法 2</option>
        {% endif %}
    </select>

</div>
<script>

</script>
<script src="{% static 'js/index.js' %}"></script>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% block title %} 数字化文物展示系统 | 登录 {% endblock title %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />

<div class="warp text-center">
  <main class="form-signin">
    <form id="form_login" action="/login/" method="post">
      <img class="mb-4" src="{% static 'media/icon.png' %}" alt="" width="80">
      <h1 class="h4 mb-4 fw-normal welcome">欢迎！</h1>

      <div class="form-floating">
        <input type="email" name="email" class="form-control" value="{{r_email}}" id="emailInput"
          placeholder="name@example.com">
        <label for="emailInput" style="color: #999;">邮箱地址</label>
      </div>
      <div class="form-floating">
        <input type="password" name="password" class="form-control" value="{{r_password}}" id="pwdInput"
          placeholder="Password">
        <label for="pwdInput" style="color: #999;">密码</label>
      </div>

      <div class="checkbox mb-3">
        <label>
          <input id="checkbox" type="checkbox" name="remember"> 记住账号和密码
        </label>
      </div>
      <button id="login_bt" class="w-100 btn btn-lg btn-dark btn-outline-light">登录</button>
    </form>
  </main>
</div>

<script src="{% static 'js/login.js' %}"></script>
{% endblock content %}

templates/register.html
{% extends 'base.html' %}
{% block title %} 数字化文物展示系统 | 注册 {% endblock title %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}" />

<div class="signup-form">
  <form action="/register/" id="register_form" method="post">
    <h2>注册</h2>
    <p>请填写表单创建新的帐号!</p>
    <hr>
    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-user"></i></span>
        <input type="text" class="form-control" name="username" placeholder="用户名" required="required" value="{{username}}">
      </div>
    </div>
    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-paper-plane"></i></span>
        <input type="email" class="form-control" name="email" placeholder="邮箱地址" required="required" value="{{email}}">
      </div>
    </div>
    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
        <input type="password" class="form-control" id="password" name="password" placeholder="密码" required="required" value="{{password}}">
      </div>
    </div>
    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-lock"></i>
          <i class="fa fa-check"></i>
        </span>
        <input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="确认密码" value="{{confirm_password}}"
          required="required">
      </div>
    </div>
    <div class="form-group">
      <button type="submit" id="register_bt" class="w-100 btn btn-lg btn-dark btn-outline-light">注册</button>
    </div>
  </form>
</div>

<!-- <script src="{% static 'js/register.js' %}"></script> -->
{% endblock content %}